  name: build and deploy fitapp
  on:
    workflow_run:
        workflows: ["Publish coverage reports"]
        branches:
            - master
        types: 
            - completed

  jobs:
    build-deploy:
      name: build and deploy fitapp
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: setup jdk 17
          uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: 17
        - name: build the app
          run: |
            mvn clean
            mvn -B package
        - name: build the docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: false
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fitapp:latest

        - name: login to docker hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: push the docker image to docker hub
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fitapp:latest